apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lease-access-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: spring-leader-election-sa
  namespace: default
roleRef:
  kind: Role
  name: lease-access-role
  apiGroup: rbac.authorization.k8s.io